language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
services:
 - redis-server
install:
 - pip install tox-travis
 - pip install coveralls
before_script:
 - createdb -E UTF-8 dash -U postgres -O $USER
script:
 - tox -- --settings=dash_test_runner.settings_travis
after_success:
 - coveralls