language: python
sudo: false
python:
 - "3.5"
 - "3.6"
addons:
  postgresql: "9.6"
env:
 - DJANGO_VERSION=1.11.14
 - DJANGO_VERSION=2.0.7
services:
 - redis-server
install:
 - pip install pip --upgrade
 - pip install -q -rrequirements/base.txt
 - pip install -q -rrequirements/tests.txt
 - pip install -q Django==$DJANGO_VERSION
 - pip install coveralls
before_script:
 - createdb -E UTF-8 dash -U postgres -O $USER
script:
 # any non-zero error code should be treated as an immediate failure
 - set -e

 # test PEP8 compliance on both Python 2 and 3
 - flake8

 # check for model changes not reflected in a migration
 - python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)

 - coverage run manage.py test --settings=dash_test_runner.settings_travis

after_success:
 - coveralls